language: cpp

compiler:
  #- clang # sadly, the travis version of clang doesn not compile our code (not our fault...)
  - gcc

before_install:
    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq

install:
    # g++4.8.1
    - if [ "$CXX" = "g++" ]; then sudo apt-get install --allow-unauthenticated -qq g++-4.8; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
    # dependencies
    - sudo apt-get install -qq libboost1.48-dev libboost-timer1.48-dev libboost-date-time1.48-dev libboost-filesystem1.48-dev libboost-program-options1.48-dev libboost-serialization1.48-dev libboost-signals1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-test1.48-dev
    - sudo apt-get install -qq liblapack-dev libfftw3-dev libx11-dev libx11-xcb-dev libxcb1-dev libxrandr-dev libxi-dev freeglut3-dev libglew1.6-dev libpng12-dev libtiff4-dev libhdf5-serial-dev

before_script:
    - mkdir build
    - cd build
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz
    - tar xf cmake-3.2.2-Linux-x86_64.tar.gz
    - ./cmake-3.2.2-Linux-x86_64/bin/cmake ..

script:
    - make
    - cd binaries/tests
    - ./testsuite
